language: node_js
node_js: "node"
script: npx gulp
before_deploy:
  - git tag "Build $(date +'%d.%m.%Y %R')" -a -m "Generated tag from TravisCI for Build $TRAVIS_BUILD_NUMBER."
deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  file_glob: true
  file: dist/*
  on:
    tag: true
    branch: master
  skip_cleanup: true